spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
      routes: #网关路由配置
        - id: user-server #路由id，自定义，只要唯一即可
          #uri: lb://user-server #路由的目标地址http就是固定地址
          uri: lb://user-server #路由的目标地址lb就是负载均衡，后面跟服务名称
          predicates: #路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/user/** #这个是按照路径匹配，只要以/user/开头就符合要求
        - id: order-server
          uri: lb://order-server
          predicates:
            - Path=/order/**
