spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
      routes: #网关路由配置
        - id: user-server #路由id，自定义，只要唯一即可
          #uri: lb://user-server #路由的目标地址http就是固定地址
          uri: lb://user-server #路由的目标地址lb就是负载均衡，后面跟服务名称
          predicates: #路由断言，也就是判断请求是否符合路由规则的条件
            - Path=/user/** #这个是按照路径匹配，只要以/user/开头就符合要求
#          filters:
#            - AddRequestHeader=Token,I'm Token
        - id: order-server
          uri: lb://order-server
          predicates:
            - Path=/order/**
      default-filters:
        - AddRequestHeader=Token,I'm token
      globalcors: #全局跨域问题解决
        add-to-simple-url-handler-mapping: true #解决options请求被拦截问题
        cors-configurations:
          '[/**]':
            #allowedOrigins: "*" #允许哪些网站跨域请求
            allowedOriginPatterns: "*" #SpringBoot升级2.4.0所出现的问题。跨域配置报错，将.allowedOrigins替换成.allowedOriginPatterns即可
            allowedMethods: #允许的跨域ajax的请求方式
              - GET
              - POST
            allowedHeaders: "*" #允许在请求中携带的头信息
            allowCredentials: true  #是否允许携带cookie
            maxAge: 360000  #这次跨域检测的有效期