# 基础镜像
FROM centos:centos7.9.2009
# 设置作者和联系方式
MAINTAINER jmlq 1072006142@qq.com
# 配置环境变量和jdk的安装目录
ENV JAVA_DIR=/usr/local
# 拷贝jdk和java项目包
COPY ./jdk-8u171-linux-x64.tar.gz $JAVA_DIR/
COPY app.jar /tmp/app.jar
# 安装jdk
# \ 就是换到下一行输入，对实际命令没有任何影响，只是为了方便观看
RUN cd $JAVA_DIR \
	# 使用tar命令将当前目录下（这里因为上面配置了所以所在的目录也就是 /usr/local/下面）的jdk文件进行解压
	&& tar -xvf ./jdk-8u171-linux-x64.tar.gz \
	# 然后修改解压后的文件名为java8 ，此时就是 /usr/local/java8
	# 这里需要注意的是下面的 jdk1.8.0_171，他就是解压后的文件名
	# 如果这里你不清楚解压后的文件是什么，则可以先解压看以下文件名是什么，然后在进行书写这里的名称
	&& mv ./jdk1.8.0_171 ./java8

# 配置JAVA的环境变量
ENV JAVA_HOME=$JAVA_DIR/java8
# 配置到PAHT中
ENV PATH=$PATH:$JAVA_HOME/bin
# 暴露端口 8080 --！！！容器内部端口
EXPOSE 8080

# 入口，jar文件的启动命令 # 这里app.jar就是我的jar文件
ENTRYPOINT ['java','-jar','/tmp/app.jar']